name: Test Bash Script

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        
        steps:
            - uses: actions/checkout@v2

            - name: Set up test environment
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo ip route add 172.16.16.0/24 dev lo
                    sudo ip route add 172.16.16.1/32 dev lo
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                    sudo route add 172.16.16.0/24 127.0.0.1
                    sudo route add 172.16.16.1/32 127.0.0.1
                  fi

            - name: Make script executable
              run: chmod +x ./your_script.sh

            - name: Run script without parameters
              run: ./your_script.sh

            - name: Run script with simple parameters
              run: ./your_script.sh param1=value1 param2=value2

            - name: Test URL encoding for unquoted parameter value with spaces
              run: |
                  gateway_check.sh=$(./your_script.sh param=value with spaces)
                  if [[ "$gateway_check.sh" == *"param=value%20with%20spaces"* ]]; then
                    echo "URL encoding test for unquoted parameter value passed"
                  else
                    echo "URL encoding test for unquoted parameter value failed"
                    exit 1
                  fi

            - name: Test URL encoding for quoted parameter value with spaces
              run: |
                  gateway_check.sh=$(./your_script.sh 'param="value with spaces"')
                  if [[ "$gateway_check.sh" == *'param="value%20with%20spaces"'* ]]; then
                    echo "URL encoding test for quoted parameter value passed"
                  else
                    echo "URL encoding test for quoted parameter value failed"
                    exit 1
                  fi

            - name: Test gateway mismatch
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo ip route del 172.16.16.1/32
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                    sudo route delete 172.16.16.1/32
                  fi
                  gateway_check.sh=$(./your_script.sh)
                  if [[ "$gateway_check.sh" == *"Default gateway"*"does not match target"* ]]; then
                    echo "Gateway mismatch test passed"
                  else
                    echo "Gateway mismatch test failed"
                    exit 1
                  fi
